name: Node Continous Integration

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.x
      - run: npm ci
      - run: ci=true npm test --silent
      - run: npm build
      - run: |
          npm install -g surge
      - run: surge ./build planitevents.surge.sh --token ${{ secrets.SURGE_TOKEN }}
